### ISSUE TITLE
Elastic Search 2.x

### ISSUE THREAD

**Issue by tomplus** [EinsamHauer/disthene#10]
Hello.

I would like to use Disthene with latest version of ElasticSearch 2.4.1 but I get

```
java.lang.IllegalStateException: Received message from unsupported version: [1.3.4] minimal compatible version is: [2.0.0]
```

Is there any reason why this old version of client library is used ?

I think it would be nice to add more info about Elastic Search (version, configuration, best topology, etc.)  to doc file.
Cyanite stopped using ES.

Thanks,
Tomasz Prus

**Comment by EinsamHauer** [comment]
Well, the answer is simple and not an unusual one - this was the most recent version when this thing started. I will test the new version and upgrade. 

Thanks for the hint about ES doc - I will add this as well. 

Andrei

**Comment by EinsamHauer** [comment]
Hmm, this is worse than I would expect - 2.x client is not compatible with pre 2.x clusters. So, there is no backward compatibility ([link](https://github.com/elastic/elasticsearch/issues/13273)). 

Upgrading the driver will mean dropping support for older cluster versions. Which may be a pain (at least I definitely see it as such for the company I'm working for)

Moreover, it's not really possible to use it w/o changing the implementation inside disthene. What I could possibly do is do it in a branch. Though I don't like the idea very much.

**Comment by tomplus** [comment]
Yes, I agree, upgrading existing cluster is complicated, risky and it requires scheduled downtime (https://www.elastic.co/guide/en/elasticsearch/reference/2.4/restart-upgrade.html). So I think the branch with 2.x client is a good option especially for new users.

Thanks,
Tomasz Prus

**Comment by kwarunek** [comment]
Maybe make use of profiles in maven and of course add a bit abstraction to indexService, This approach would facilitate further upgrades, I think.

**Comment by EinsamHauer** [comment]
Yep, will handle this - just need some time (primarily for tests)

**Comment by EinsamHauer** [comment]
This was done a long time ago in fact
