### ISSUE TITLE
Upgrade of cassandra driver

### ISSUE THREAD

**Issue by kwarunek** [EinsamHauer/disthene#12]
Hi,

Do you consider upgrade of cassandra-driver-core? The newest version - 3.1 (https://docs.datastax.com/en/developer/java-driver/3.1/) has many improvements, but the most important it will enable upgrade to C* 3.x - https://docs.datastax.com/en/developer/java-driver/3.1/manual/native_protocol/.

**Comment by EinsamHauer** [comment]
Sure, I will do this. 

I tested it quickly and I'm having strange problems connecting to C* 2.0 with drivers newer than 3.1.0, but 3.1.0 works just fine. 

Also, it will require introducing another setting (ProtocolVersion) to support both 2.* and 3.* C*. 

I'll try to do this over the weekend.

**Comment by kwarunek** [comment]
Great news. Thx

**Comment by EinsamHauer** [comment]
This is done. Also for [disthene-reader](https://github.com/EinsamHauer/disthene-reader).
(Even though I still don't know why driver versions > 3.1.1 are not able to connect to my cluster)

**Comment by kwarunek** [comment]
Thanks. I 'll he try it tomorrow. Also I can test the 3.2 with our set up: C* 2.1.9 on 1.7.0_60-b19.

**Comment by EinsamHauer** [comment]
Please, let me know. I'm curious about 2.1.9 and 3.2 driver.
