### ISSUE TITLE
Migration to 2.x

### ISSUE THREAD

**Issue by kwarunek** [EinsamHauer/disthene#23]
hi,

First of all as always awesome work - thanks for the disthene. 

I would like to migrate do 2.x from 1.x, could you describe  briefly changes and migration process? testing

- Are there changes in C*/ES scheme?
- Any breaking changes from the user stand point - graphite api/ aggregation?
- Tips?

We'll be testing k8ssandra (maybe scylla as well) + AWS OpenSearch (probably req signing will be required) setup.

**Comment by EinsamHauer** [comment]
Hi, 

The changes are mostly related to using the newer versions of C* and ES. Also there are some algorithmic optimization here and there. In general it's somewhat faster, defintely so for the reads.

- Unfortunately (for the migration purposes) there is a change to C* schema. Now it uses separate tables per tenant/rollup. And corresponding fields are removed from the table itself. At some point there was code to support migration (i.e. new data were written to the new schema but both old and new were queried by disthene-reader (So this code is in disthene-reader actually). The new tables are created automatically by disthene. (Controlled by config around here https://github.com/EinsamHauer/disthene/blob/version-2.0/src/main/java/net/iponweb/disthene/config/StoreConfiguration.java#L26).
The rationale behind this change is that it saves disk space on cassandra nodes as individual tables are smaller and require less space for compaction
- No, from user/etc standpoint it's 100% compatible/unchanged
- None so far. The biggest problem is migrating cassandra data. Heavily depends on the volume. I've ended up writing a program that reads old C* snapshots and writes them to new C*/ES. Thus no special migration for ES data

**Comment by kwarunek** [comment]
Thank you. Regarding the migration in our case is not a problem - max rollup 14d (we'll simply configure the carbon-c-relay to additionally forward to a new cluster for two weeks).
