### ISSUE TITLE
Can you explain which version cyanite compatible?

### ISSUE THREAD

**Issue by youtome** [EinsamHauer/disthene#5]
Hi EinsamHauer.
I interest your project.
When I test this project for write I think is good.
But When I want to use for read a project I can't read from cyanite.

Can you explain which version cyanite compatible?

I can't write English very well.

Thank you.

**Comment by EinsamHauer** [comment]
Hi @youtome 

Unfortunately, it was compatible only at some point. Also unfortunate is that cyanite has no versions/releases it seems. 

But the point in time it was compatible is somewhere around here:
https://github.com/pyr/cyanite/tree/ab601365d825e457077e0707d1451c83d5408534

Current versions of cyanite are completely different. Probably, I should update the readme and remove compatibility thing.

**Comment by aww-yiss** [comment]
Hi @EinsamHauer 

I've just recently found this project while trying to find solutions for bottle necks I'm encountering with cyanite at the moment. I've been testing with the current mater release (0.5.1) and as you noted its quite a different engine, and the ES index seems to have been deprecated in favor of storing this within the metic keyspace. Do you think you'll try to build compatibility with the new schema layout?

If not, any suggestions or recommendations for the ES setup you worked with would be beneficial and appreciated

**Comment by EinsamHauer** [comment]
Hi @aww-yiss 

No, I don't think I'll be trying to keep up with cyanite - this is a different project already and the migration path will be very complicated.
On the other hand, I do still think that using ES in this case is a bright idea. 

The setup we are working with is:
- 2 ES data nodes with replication factor 2. Smaller instances (we are working on EC2) like c4.2xlarge or c4.xlarge
- ES "client" node on every dithene/disthene-reader host - this costs nothing but makes latencies slightly better

The setup above allows us to store like ~10M data points per minute currently and to sustain like ~1.5K "render" requests per minute. It feels like no ES extension will be needed if we go up to, say, 30M per minute.
