### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by kwarunek** [EinsamHauer/disthene#6]
In whisper based set up, there is possibility to alias a metric, just using the symlinks. Let's say:

```
drwxr-xr-x 8 graphite graphite 4096 Dec 14 08:28 ../
lrwxrwxrwx 1 graphite     graphite       32 Dec 14 08:28 kern_err.wsp -> ../Applications/kernel/error.wsp
```

It is dead simple. The main drawback is managing and  the nature of symlink itself.

To cut to the chase, I am missing this function in disthene.  I could provide PR, it requires to change a bit writer, reader and finder, new field in metric index `is_alias_of`, also new db (simple k->v) for aliases (cassandra or es)ll .  

Do you have any plans, thoughts, recommendations?

**Comment by EinsamHauer** [comment]
@kwarunek, what's the use case/scenario where you'd need this? (A priori, I would be reluctant to do something like this)

**Comment by kwarunek** [comment]
Let's say there are metric like (within the same tenant):
`m1.vm1.cpu`
`m1.vm2.cpu`
`m2.some.metric`
Team M1 sees only metrics `m1.*`, and M2 sees only `m2.*` - the filter can be implemented as the grafana's custom datasource or in webapp's cyanite-finder - actually we are mixing these two approaches.

The case is to share (alias) some metrics of M1 to be available for M2.

Of course, we were thinking of using `tenant` feature to separate, but:
- currently, for each team there must be a writer, that sounds like 1k writers,
- case, user/team has access to many tenants, mixing charts from many tenants
- despite all above there is still problem of sharing **only some branch/part** of metric

Aliasing vs duplication metrics (data) - our dataset is fast growing, right now duplication means additional couple millions of inserts per minute.

**Comment by EinsamHauer** [comment]
@kwarunek 
- i don't get it abut separate/1k writers. Just FTR the setup we are running has like >50 tenants writing like ~15M per minute with just 2 disthenes and 2 just for redundancy
- unfortunately I cannot think of a clean and efficient way to implement what you are suggesting. In any case it will add quite some overhead. Besides that, it will probably not fit with other concepts, like aggregation.
- OTOH, I'm interested in how you would implement. I have another use case - renaming, say, servers. It was easy in whisper, but not possible in cyanite/disthene so far. The aliasing thing seems to be somewhere in that area as well.

**Comment by kwarunek** [comment]
1. you have right, separate writer per tenant is unnecessary, I was misinformed . But still there is a problem with whole graphite ecosystem that is not aware of tenant field in line protocol (I cannot drop support for this) or am I again missing something?
2. That's right it will produce overhead, even more we are have own aggregation system, before disthene, so we are not aware of the implications .

**Comment by EinsamHauer** [comment]
> But still there is a problem with whole graphite ecosystem that is not aware of tenant field in line protocol (I cannot drop support for this) or am I again missing something?

You are absolutely right, unfortunately. I haven't come up with a better idea on how to tackle this yet
